spring.application.name=WB_LABELPRINT

server.port=8181
spring.thymeleaf.cache=false

# USA DB
spring.datasource.url=jdbc:log4jdbc:oracle:thin:@45.58.2.218:1521:WBUSA
spring.datasource.username=wbusa
spring.datasource.password=woobo23300usa
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

# Mybatis Settings
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.example.wb_usa_labelprint


# 운영 배포용 Thymeleaf / Static
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.web.resources.static-locations=classpath:/static/


logging.level.log4jdbc.log4j2=off
logging.level.root=info
logging.level.jdbc=off
logging.level.jdbc.sqlonly=info
logging.level.jdbc.sqltiming=off
logging.level.jdbc.resultsettable=info
logging.level.jdbc.audit=off
logging.level.jdbc.resultset=off
logging.level.jdbc.connection=off