spring.application.name=WB_LABELPRINT

server.port=8181
server.servlet.session.cookie.name=WB_LABELPRINT_JSESSIONID

# USA DB
datasource.usa.jdbc-url=jdbc:log4jdbc:oracle:thin:@45.58.2.218:1521:WBUSA
datasource.usa.username=wbusa
datasource.usa.password=woobo23300usa
datasource.usa.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

# MEX DB
datasource.mex.jdbc-url=jdbc:log4jdbc:oracle:thin:@187.191.63.113:1521:WBMEX
datasource.mex.username=wbmex
datasource.mex.password=woobo23300mex
datasource.mex.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

# POL DB
datasource.pol.jdbc-url=jdbc:log4jdbc:oracle:thin:@176.122.244.138:1521:REXPOL
datasource.pol.username=rexpol
datasource.pol.password=inbus
datasource.pol.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

# KOR DB
datasource.kor.jdbc-url=jdbc:log4jdbc:oracle:thin:@218.147.154.81:1521:INBUS
datasource.kor.username=REXERP
datasource.kor.password=INBUS
datasource.kor.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy


# Mybatis Settings
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.example.wb_usa_labelprint


logging.level.log4jdbc.log4j2=off
logging.level.root=info
logging.level.jdbc=off
logging.level.jdbc.sqlonly=info
logging.level.jdbc.sqltiming=off
logging.level.jdbc.resultsettable=info
logging.level.jdbc.audit=off
logging.level.jdbc.resultset=off
logging.level.jdbc.connection=off